export const Images = {
  username: require('./username.png'),
  password: require('./password.png'),
  buttonSee: require('./buttonseeall.png'),
  email: require('./email.png'),
  apparel: require('./apparel.png'),
  beauty: require('./beauty.png'),
  Electronics: require('./Electronics.png'),
  home: require('./home.png'),
  stationary: require('./stationary.png'),
  furniture: require('./furniture.png'),
  shoes: require('./shoes.png'),
  seeAllBig: require('./sellallBig.png'),
  slider1: require('./Slider1.png'),
  slider2: require('./slider2.png'),
  boot: require('./ankletboot.png'),
  bag: require('./bag.png'),
  scarf: require('./scart.png'),
  cross: require('./cross.png'),
  tabHome: require('./TabHome.png'),
  TabSearch: require('./TabSearch.png'),
  TabCart: require('./TabCart.png'),
  TabProfile: require('./TabProfile.png'),
  tabMore: require('./tabMore.png'),
  promoCode: require('./promocode.png'),
  smallArrow: require('./smallarrow.png'),
};
